### PR TITLE
[NCL-8939] Set single page request to page size 0

### PR DESCRIPTION
**Pull request by patrikk0123**

### CODE REVIEW

**Review by matedo1 — APPROVED** [review]
Great, thanks!

**Comment by matedo1** [comment]
This PR can be merged after backend support (NCL-8275) is fully deployed.

**Comment by patrikk0123** [comment]
The relevant backend change is now available on prod environment

**Comment by matedo1** [comment]
@patrikk0123 If there are no other updates required, you can merge it

**Pull request merged**
