### PR TITLE
[NCL-8775] Make ssh details visible for admin users

### PR DESCRIPTION
**Pull request by DnsZhou**
This PR is on hold due to missing backend support, see NCL-8756.

### CODE REVIEW

**Comment by patrikk0123** [comment]
looks good, is it stil meant to be a draft?

**Comment by DnsZhou** [comment]
> looks good, is it stil meant to be a draft?

@patrikk0123 due to NCL-8756, this pr has to remain on hold because backend support for fetching the ssh details by pnc admin user is not implemented.

**Comment by matedo1** [comment]
Will it start working automatically once backend support is ready? If yes and there is currently no other issue being present (?), then we can merge it?

**Comment by DnsZhou** [comment]
> Will it start working automatically once backend support is ready? If yes and there is currently no other issue being present (?), then we can merge it?

Yes, as long as the backend supports, this change would be valid. I will merge it now.

**Comment by DnsZhou** [comment]
moved to https://github.com/project-ncl/pnc-web-ui-react/pull/555

**Pull request closed without merging**
