### PR TITLE
[NCL-7980] Integrate entity attributes into Product pages

### PR DESCRIPTION
**Pull request by patrikk0123**

### CODE REVIEW

**Comment by patrikk0123** [comment]
@matedo1 Are tooltips needed for titles of these attributes?

**Comment by matedo1** [comment]
@patrikk0123 Let's skip them for now, there is just one rule - if tooltips are available on one page (for example create page), then they have to applied also on all other pages (detail, list, etc).

**Review by matedo1 — CHANGES_REQUESTED** [review]
Thanks! I was able to find some additional places:
- ProductMilestoneReleaseLabel.tsx

**Review by matedo1 — APPROVED** [review]
Thanks!

**Pull request merged**
